# Generated by Django 4.2.1 on 2023-06-17 12:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DonationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
                ("subtitle", models.CharField(max_length=4096)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DonationTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.CharField(max_length=1024)),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(10000)]
                    ),
                ),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TierFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature", models.CharField(max_length=512)),
                (
                    "donation_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donations.donationtier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DonationInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("whatsapp_number", models.CharField(max_length=12)),
                ("occupation", models.CharField(max_length=512)),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(10000)]
                    ),
                ),
                ("address", models.TextField(max_length=4096)),
                ("payment_date_time", models.DateTimeField()),
                (
                    "donation_tier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="donations.donationtier",
                    ),
                ),
            ],
        ),
    ]
