# Generated by Django 4.2.1 on 2024-12-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationtier",
            name="visible",
            field=models.BooleanField(
                default=False, verbose_name="Show on Donations Page ?"
            ),
        ),
    ]
