# Generated by Django 4.2.1 on 2023-06-17 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DonationInstance",
            new_name="DonationReceived",
        ),
    ]
