# Generated by Django 4.2.1 on 2023-06-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0002_rename_donationinstance_donationreceived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationreceived",
            name="payment_date_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
