# Generated by Django 4.2.1 on 2023-06-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0003_alter_donationreceived_payment_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationreceived",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failure", "Failure"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
