# Generated by Django 4.2.1 on 2023-12-16 06:57

from django.db import migrations, models
import utils.images


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommunityActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Group Study", max_length=512)),
                (
                    "summary",
                    models.CharField(
                        default="Activity description in short", max_length=1024
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Detailed activity description", max_length=10240
                    ),
                ),
                (
                    "fa_icon",
                    models.TextField(
                        default="fa-solid fa-graduation-cap", max_length=100
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=utils.images.upload_image_to
                    ),
                ),
            ],
        ),
    ]
