# Generated by Django 4.2.1 on 2024-01-01 20:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityactivity",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="communityactivity",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="communityactivity",
            name="description",
            field=models.TextField(
                default="Detailed activity description", max_length=1024
            ),
        ),
    ]
