# Generated by Django 4.2.1 on 2024-01-01 19:35

from django.db import migrations, models
import utils.images


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_blogpost_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=utils.images.upload_image_to
            ),
        ),
    ]
