# Generated by Django 4.2.1 on 2023-06-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeCarousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HomeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="Temple Web", max_length=255)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("map_embed_url", models.CharField(default="helllo", max_length=5000)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomeGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("link", models.CharField(default="/", max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="FooterLinkCateg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categ_title", models.CharField(max_length=100)),
                (
                    "home_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.homeconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NavLink",
            fields=[
                (
                    "link_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.link",
                    ),
                ),
                (
                    "home_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.homeconfig",
                    ),
                ),
            ],
            bases=("home.link",),
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "link_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.link",
                    ),
                ),
                (
                    "footer_link_categ",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.footerlinkcateg",
                    ),
                ),
            ],
            bases=("home.link",),
        ),
    ]
