# Generated by Django 4.2.1 on 2023-06-21 06:31

from django.db import migrations, models
import django.db.models.deletion
import utils.images


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="Temple Web", max_length=255)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("favicon", models.ImageField(upload_to=utils.images.upload_image_to)),
                ("logo", models.ImageField(upload_to=utils.images.upload_image_to)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomeContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("map_embed_url", models.CharField(default="helllo", max_length=5000)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("link", models.CharField(default="/", max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ModelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt_text", models.CharField(max_length=512)),
                ("redirect_url", models.URLField()),
                ("image", models.ImageField(upload_to=utils.images.upload_image_to)),
            ],
        ),
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "modelimage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.modelimage",
                    ),
                ),
            ],
            bases=("home.modelimage",),
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "modelimage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.modelimage",
                    ),
                ),
            ],
            bases=("home.modelimage",),
        ),
        migrations.CreateModel(
            name="FooterLinkCateg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categ_title", models.CharField(max_length=100)),
                (
                    "home_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.homeconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CallToAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Call to Action Card", max_length=256),
                ),
                ("description", models.CharField(max_length=1024)),
                ("button_text", models.CharField(max_length=32)),
                (
                    "home_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.homecontent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NavLink",
            fields=[
                (
                    "link_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.link",
                    ),
                ),
                (
                    "home_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.homeconfig",
                    ),
                ),
            ],
            bases=("home.link",),
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "link_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.link",
                    ),
                ),
                (
                    "footer_link_categ",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.footerlinkcateg",
                    ),
                ),
            ],
            bases=("home.link",),
        ),
    ]
