# Generated by Django 4.2.1 on 2023-06-18 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("map_embed_url", models.CharField(default="helllo", max_length=5000)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="homeconfig",
            name="map_embed_url",
        ),
        migrations.CreateModel(
            name="CallToAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Call to Action Card", max_length=256),
                ),
                ("description", models.CharField(max_length=1024)),
                ("button_text", models.CharField(max_length=32)),
                (
                    "home_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.homecontent",
                    ),
                ),
            ],
        ),
    ]
