# Generated by Django 4.2.1 on 2023-07-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_calltoaction_fa_icon_sociallink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sociallink",
            name="fa_icon",
        ),
        migrations.AddField(
            model_name="sociallink",
            name="icon_brand",
            field=models.CharField(default="facebook", max_length=20),
        ),
    ]
