# Generated by Django 4.2.1 on 2023-06-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="test_image",
            field=models.ImageField(upload_to=""),
        ),
    ]
