# Generated by Django 4.2.1 on 2024-02-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_homecontent_activity_heading"),
    ]

    operations = [
        migrations.AddField(
            model_name="homecontent",
            name="blog_count",
            field=models.PositiveIntegerField(default=4),
        ),
    ]
