# Generated by Django 4.2.1 on 2023-08-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_calltoaction_cta_type_alter_calltoaction_button_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calltoaction",
            name="link",
            field=models.CharField(default="/", max_length=256),
        ),
    ]
