# Generated by Django 4.2.1 on 2023-08-20 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_calltoaction_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="homecontent",
            name="activity_subhead",
            field=models.CharField(
                default="Here at Temple we focus on overall wellbeing and development.",
                max_length=512,
            ),
        ),
        migrations.CreateModel(
            name="FooterAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aline1",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Address Line 1",
                    ),
                ),
                (
                    "aline2",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Address Line 2",
                    ),
                ),
                (
                    "aline3",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Address Line 3",
                    ),
                ),
                (
                    "contact_no",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        verbose_name="Contact Phone no",
                    ),
                ),
                (
                    "site_config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.siteconfig",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
