# Generated by Django 4.2.1 on 2023-07-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_sociallink_fa_icon_sociallink_icon_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="icon_brand",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
