# Generated by Django 4.2.1 on 2023-06-16 19:12

from django.db import migrations, models

import home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_image_test_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="test_image",
            field=models.ImageField(upload_to=home.models.upload_to),
        ),
    ]
