# Generated by Django 4.2.1 on 2023-08-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_footeraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="homecontent",
            name="activity_subhead",
            field=models.CharField(
                default="Here at Temple we focus on overall wellbeing and development.",
                max_length=512,
            ),
        ),
    ]
