# Generated by Django 4.2.1 on 2023-12-29 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.images


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_templewebuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(upload_to=utils.images.upload_image_to),
                ),
                ("address", models.TextField(max_length=1024)),
                ("profession", models.CharField(max_length=256)),
                ("whatsapp_number", models.CharField(max_length=15)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
