# Generated by Django 4.2.1 on 2023-12-29 23:22

from django.db import migrations, models
import utils.images


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to=utils.images.upload_image_to
            ),
        ),
    ]
