# Generated by Django 4.2.1 on 2023-12-23 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.images


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(max_length=4096)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=utils.images.upload_image_to
                    ),
                ),
                ("venue", models.CharField(max_length=128)),
                ("start_time", models.DateField()),
                ("end_time", models.DateField(blank=True, null=True)),
                (
                    "accept_reg",
                    models.BooleanField(verbose_name="Accepting registrations ?"),
                ),
                (
                    "show_on_home",
                    models.BooleanField(verbose_name="Show on Home Page ?"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="haps.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
