# Generated by Django 4.2.1 on 2023-12-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("haps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
