# Generated by Django 4.2.1 on 2023-12-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("haps", "0002_alter_event_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
