# Generated by Django 4.2.1 on 2024-12-27 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("haps", "0004_event_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="login_required",
            field=models.BooleanField(
                default=True, verbose_name="Login required for registration?"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_fee",
            field=models.PositiveIntegerField(
                blank=True, help_text="Leave blank for free registration", null=True
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="form_responses",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failure", "Failure"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="EventFormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_label", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Input"),
                            ("number", "Number Input"),
                            ("email", "Email Input"),
                            ("textarea", "Text Area"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("help_text", models.CharField(blank=True, max_length=200)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_fields",
                        to="haps.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("event", "field_label")},
            },
        ),
    ]
