# Generated by Django 4.2.1 on 2023-07-21 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensecategory",
            name="category_balance",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Balance"
            ),
        ),
        migrations.AlterField(
            model_name="transanction",
            name="fund_raiser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.fundraiser",
            ),
        ),
    ]
