# Generated by Django 4.2.1 on 2023-08-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_transanction_signed_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name="transanction",
            name="txn_status",
            field=models.CharField(
                blank=True,
                choices=[("DUE", "⏳ Due"), ("PAID", "✅ Paid")],
                max_length=12,
                null=True,
                verbose_name="Transanction Status",
            ),
        ),
        migrations.AddField(
            model_name="transanction",
            name="mode",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.paymentmode",
            ),
        ),
    ]
