# Generated by Django 4.2.1 on 2023-08-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_paymentmode_transanction_txn_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillerDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "biller_name",
                    models.CharField(default="Biller Name", max_length=256),
                ),
                (
                    "biller_address",
                    models.TextField(default="Biller Address", max_length=2048),
                ),
                ("biller_phone", models.CharField(default="9999999999", max_length=12)),
                (
                    "biller_email",
                    models.CharField(default="biller@example.com", max_length=64),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
