# Generated by Django 4.2.1 on 2023-08-19 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_adminlinkmodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdminLinkModel",
            new_name="GetStatement",
        ),
        migrations.CreateModel(
            name="Link2",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.getstatement",),
        ),
    ]
