# Generated by Django 4.2.1 on 2023-08-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_rename_adminlinkmodel_getstatement_link2"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminLinkModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GetStatement",
        ),
        migrations.DeleteModel(
            name="Link2",
        ),
        migrations.CreateModel(
            name="GetStatement",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.adminlinkmodel",),
        ),
    ]
